[package]
name = "wisp"
version = "0.1.0"
authors = ["obscurity <z@x4.pm>"]
edition = "2021"

[dependencies]
serenity = { version = "0.11", features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
    "cache",
], default-features = false }
poise = "0.4"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }

kankyo = "0.3"
paris = { version = "1.5", features = ["timestamps", "macros"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"

chrono = "0.4"
chrono-tz = "0.8"
ureq = { version = "2.6", features = ["json"] }
lazy_static = "1.4"
nanorand = "0.7"
system_shutdown = "4.0"

[profile.release]
lto = true
strip = true
codegen-units = 1
