[package]
name = "wisp"
version = "0.2.1"
authors = ["fawn <fawn@envs.net>"]
edition = "2021"
repository = "https://github.com/fawni/wisp"
license = "ISC"

[dependencies]
serenity = { version = "0.11", features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
    "cache",
], default-features = false }
poise = "0.5"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }

kankyo = "0.3"
paris = { version = "1.5", features = ["timestamps", "macros"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"

chrono = "0.4"
chrono-tz = "0.8"
ureq = { version = "2.6", features = ["json"] }
lazy_static = "1.4"
nanorand = "0.7"
system_shutdown = "4.0"

[profile.release]
lto = true
codegen-units = 1

[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
