[package]
name = "wisp"
version = "0.3.0"
authors = ["fawn <fawn@envs.net>"]
edition = "2021"
repository = "https://github.com/fawni/wisp"
license = "ISC"

[dependencies]
poise = "0.5.6"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }

serde = { version = "1.0.188", features = ["derive"] }
twink = { version = "1.1.0", features = ["12-hour"] }
dotenvy = "0.15.7"
thiserror = "1.0.48"

reqwest = { version = "0.11.20", features = ["json"] }
nanorand = "0.7.0"
regex = "1.9.5"

chrono = "0.4.30"
chrono-tz = "0.8.3"

system_shutdown = "4.0.1"
once_cell = "1.18.0"

[profile.release]
lto = true
codegen-units = 1
