[package]
name = "wisp"
version = "0.1.0"
authors = ["obscurity <z@x4.pm>"]
edition = "2021"

[dependencies]
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
kankyo = "0.3"
poise = "0.3"
paris = { version = "1.5", features = ["timestamps", "macros"] }
color-eyre = "0.6"

[dependencies.serenity]
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "cache"]
version = "0.11"