services:
  bot:
    image: fawni/wisp # or ghcr.io/fawni/wisp or codeberg.org/fawn/wisp
    # build: . # uncomment to build the image locally instead of pulling from a registry
    restart: unless-stopped
    environment:
      WISP_PREFIX: "~"
      WISP_TOKEN: ""
      WISP_COLOR: "8AB484" # a hex string without the '#'
      WOLFRAM_APP_ID: "" # wolfram app id from https://developer.wolframalpha.com/access
      
